name: Collecting Chests
main: com.gmail.zimmerlint.plugin.CollectingChests
version: 0.6
commands:
   collectChest:
      description: Collecting Chests
      usage: 
      permission: CollectingChests.collectChest
      permission-message: You don't have <permission>
      aliases: cc